# NB: this name is used in the status badge
name: "Tests, code style & coverage"

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - dev
      - main

# Copied from travis.yml, might need to be re-included
#env:
#  global:
#    - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
#    - SEGFAULT_SIGNALS=all
#    - LANG=en_US.UTF-8

jobs:
  build:
    name: Tests (${{ matrix.platform }})
    runs-on: ${{ matrix.platform }}

    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
        exclude:
          - platform: macos-latest
      max-parallel: 4
      fail-fast: false

    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
          python-version: "3.7"
      - uses: "actions/setup-python@v2"
        with:
          python-version: "3.8"
      - name: "Install dependencies"
        run: |
          python -mpip install --progress-bar=off tox -r'ci/requirements.txt'
          virtualenv --version
          pip --version
          tox --version
          which python3.7
          which python3.8
      - name: "Run tox"
        run: "python -m tox -vv"
